# Generated by Django 6.0.3 on 2026-03-17 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keitaro_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('geo', models.CharField(max_length=10)),
                ('domain', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keitaro_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keitaro_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('stream_type', models.CharField(choices=[('google', 'Google Redirect'), ('offer', 'Offer Stream')], default='offer', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='wrapper_keitaro.campaign')),
            ],
            options={
                'unique_together': {('keitaro_id', 'campaign')},
            },
        ),
        migrations.CreateModel(
            name='StreamOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('pinned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrapper_keitaro.offer')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='wrapper_keitaro.stream')),
            ],
            options={
                'unique_together': {('stream', 'offer')},
            },
        ),
    ]
